version: 0.2
env:
  variables:
    stackname: "ec2-gpu-roles"
    cloudfile: "ec2-roles.yml"
    stackname1: "ec2-gpu"
    cloudfile1: "ec2.yml"
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - | 
          STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${stackname} 2> /dev/null | jq .Stacks | jq .[0] | jq .StackStatus | xargs) 
          echo $STACK_STATUS
          if [ "ROLLBACK_COMPLETE" == "${STACK_STATUS}" ]; then
            echo stack is in ROLLBACK_COMPLETE delete it
            aws cloudformation delete-stack --stack-name ${stackname}
            aws cloudformation wait stack-delete-complete --stack-name ${stackname}
            aws cloudformation create-stack --stack-name ${stackname} --template-body file://${cloudfile} --capabilities CAPABILITY_NAMED_IAM
            aws cloudformation wait stack-create-complete --stack-name ${stackname}
          else            
            if [ "x" == "x${STACK_STATUS}" ]; then
              echo stack doesnt exist, create it
              aws cloudformation create-stack --stack-name ${stackname} --template-body file://${cloudfile} --capabilities CAPABILITY_NAMED_IAM
              aws cloudformation wait stack-create-complete --stack-name ${stackname}
            else
              echo stack exists but isnt rolled back,  update it
              aws cloudformation update-stack --stack-name ${stackname} --template-body file://${cloudfile} --capabilities CAPABILITY_NAMED_IAM
            fi
          fi
          STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${stackname1} 2> /dev/null | jq .Stacks | jq .[0] | jq .StackStatus | xargs) 
          echo $STACK_STATUS
          if [ "ROLLBACK_COMPLETE" == "${STACK_STATUS}" ]; then
            echo stack is in ROLLBACK_COMPLETE delete it
            aws cloudformation delete-stack --stack-name ${stackname1}
            aws cloudformation wait stack-delete-complete --stack-name ${stackname1}
            aws cloudformation create-stack --stack-name ${stackname1} --template-body file://${cloudfile1}
          else            
            if [ "x" == "x${STACK_STATUS}" ]; then
              echo stack doesnt exist, create it
              aws cloudformation create-stack --stack-name ${stackname1} --template-body file://${cloudfile1}
            else
              echo stack exists but isnt rolled back,  update it
              aws cloudformation update-stack --stack-name ${stackname1} --template-body file://${cloudfile1}
            fi
          fi
