AWSTemplateFormatVersion: 2010-09-09
Resources:
  EC2GPUInstance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0994f630ee26a4ce7
      KeyName: ec2awskey
      InstanceType: p2.xlarge
      IamInstanceProfile: Ec2InstanceProfile
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            cd /home/ec2-user/anaconda3/bin >> /home/ec2-user/cloudlogs
            source activate pytorch_latest_p36 >> /home/ec2-user/cloudlogs

            cd /opt >> /home/ec2-user/cloudlogs
            mkdir nn >> /home/ec2-user/cloudlogs
            cd nn >> /home/ec2-user/cloudlogs
            git clone https://github.com/peci1/nvidia-htop >> /home/ec2-user/cloudlogs
            cd nvidia-htop >> /home/ec2-user/cloudlogs
            pip3 install . >> /home/ec2-user/cloudlogs
            cd /opt >> /home/ec2-user/cloudlogs
            git clone https://github.com/KenKaprielian/AWS-EMR-Pytorch-MultiGPU-Distribution.git >> /home/ec2-user/cloudlogs

            cd AWS-EMR-Pytorch-MultiGPU-Distribution >> /home/ec2-user/cloudlogs

            aws s3 cp s3://kens3bucketmm/deeplearning/data.zip data.zip >> /home/ec2-user/cloudlogs
            unzip data.zip  >> /home/ec2-user/cloudlogs # unzip the ant and bee pictures

            nvidia-smi daemon -d 1  >> /home/ec2-user/cloudlogs # start the nvidia-smi log daemo with a 1 second interval

            python3 pytorch.py  >> /home/ec2-user/cloudlogs # start training

            nvidia-smi daemon -t  >> /home/ec2-user/cloudlogs # stop the nvidia-smi log daemon

            zip -r nvidia-smi-logs.zip /var/log/nvstats/   >> /home/ec2-user/cloudlogs # zip smi the logs up
            zip -r gpu-logs.zip /opt/AWS-EMR-Pytorch-MultiGPU-Distribution/gpulog*   >> /home/ec2-user/cloudlogs # zip the h top gpu logs up
            aws s3 cp  nvidia-smi-logs.zip s3://kens3bucketmm/deeplearning/nvidia-smi-logs.zip  >> /home/ec2-user/cloudlogs # send the logs to S3 for safekeeping, as this instance will be terminated
            aws s3 cp  gpu-logs.zip s3://kens3bucketmm/deeplearning/gpu-logs.zip >> /home/ec2-user/cloudlogs
