AWSTemplateFormatVersion: '2010-09-09'
Resources:
  emrpytorchgpucluster:
    Type: AWS::EMR::Cluster
    Properties:
      EbsRootVolumeSize: 20
      Instances:
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: c4.large
          Market: ON_DEMAND
          Name: GPU-Pytorch-Master
        CoreInstanceGroup:
          InstanceCount: 2
          InstanceType: p3.8xlarge
          Market: ON_DEMAND
          Name: GPU-Pytorch-Core
        TerminationProtected: false
        Ec2SubnetId: subnet-6399003f
      Name: GPU-Pytorch-Cluster
      JobFlowRole: !Ref emrEc2InstanceProfile
      ServiceRole: !Ref emrRole
      ReleaseLabel: emr-6.1.0
      VisibleToAllUsers: true
  emrRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: elasticmapreduce.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole'
  emrEc2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role'
  emrEc2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref emrEc2Role
